version: '3.1'

volumes:
  pgdata:

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=memberships
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - pgdata:/var/lib/postgresql/data/

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: "tail -f /dev/null"

  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
