# Generated by Django 2.0.4 on 2018-04-30 00:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=317)),
                ('description', models.TextField()),
                ('fee', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('legal_id', models.PositiveIntegerField(unique=True)),
                ('registration_date', models.DateField()),
                ('has_student_certificate', models.BooleanField(default=False)),
                ('has_subscription_letter', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.Category')),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=317)),
                ('contact_info', models.TextField(blank=True)),
                ('document_number', models.CharField(blank=True, help_text='CUIT, etc.', max_length=317)),
                ('address', models.CharField(blank=True, max_length=2048)),
                ('social_media', models.TextField(blank=True)),
                ('membership', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='members.Member')),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=317)),
                ('email', models.EmailField(max_length=1024)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('timestamp', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('platform', models.CharField(choices=[('mercado pago', 'Mercado Pago'), ('todo pago', 'Todo Pago'), ('transfer', 'transferencia bancaria')], default='mercado pago', max_length=317)),
                ('id_in_platform', models.CharField(max_length=317)),
                ('comments', models.TextField(blank=True)),
                ('patron', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Patron')),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('first_name', models.CharField(max_length=317)),
                ('last_name', models.CharField(max_length=317)),
                ('document_number', models.CharField(blank=True, max_length=317)),
                ('email', models.EmailField(max_length=1024)),
                ('nickname', models.CharField(blank=True, max_length=317)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('nationality', models.CharField(blank=True, max_length=317)),
                ('marital_status', models.CharField(blank=True, max_length=317)),
                ('occupation', models.CharField(blank=True, max_length=317)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('street_address', models.CharField(blank=True, max_length=317)),
                ('zip_code', models.CharField(blank=True, max_length=317)),
                ('city', models.CharField(blank=True, max_length=317)),
                ('province', models.CharField(blank=True, max_length=317)),
                ('country', models.CharField(blank=True, max_length=317)),
                ('membership', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to='members.Member')),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2015)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('invoice_id', models.CharField(blank=True, max_length=317)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Member')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Payment')),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.PaymentStrategy'),
        ),
        migrations.AddField(
            model_name='member',
            name='patron',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary', to='members.Patron'),
        ),
    ]
