# Generated by Django 2.0.4 on 2018-04-30 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='membership',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Member'),
        ),
    ]
