# Generated by Django 2.0.4 on 2018-04-30 17:57

from django.db import migrations


CATEGORIES = {
    'Activo': {
        'description': "Participación Completa (Voz y Voto). Realiza un aporte económico y es elegible para cargos directivos.",
        'fee': 200
    },
    'Adherente': {
        'description': "Participación parcial (Voz). Realiza un aporte económico diferenciado. Entusiastas y Profesionales.",
        'fee': 75
    },
    'Estudiante': {
        'description': "Aporte económico simbólico. Alumnos Regulares",
        'fee': 25
    },
    'Colaborador': {
        'description': "Participación (Voz). Proyectos Software Libre / Voluntarios Eventos PyAr",
        'fee': 0
    },
    'Cadete': {
        'description': "Si sos menor de 18 años perteneces a esta categoría y vas a ser becado.",
        'fee': 0
    },
}

def set_category(apps, schema_editor):
    Category = apps.get_model('members', 'Category')
    for name in ('Activo', 'Adherente', 'Estudiante', 'Colaborador', 'Cadete'):
        category, created = Category.objects.get_or_create(
            name=name,
            defaults={
                'description': CATEGORIES.get(name)["description"],
                'fee': CATEGORIES.get(name)["fee"]
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180430_2303'),
    ]

    operations = [
        migrations.RunPython(set_category, migrations.RunPython.noop)
    ]
