# Generated by Django 2.0.4 on 2018-05-01 02:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20180430_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='comments',
            field=models.TextField(blank=True, verbose_name='comentarios'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(verbose_name='descipción'),
        ),
        migrations.AlterField(
            model_name='category',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='cuota mensual'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=317, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.Category', verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='member',
            name='has_student_certificate',
            field=models.BooleanField(default=False, verbose_name='tiene certificado de estudiante?'),
        ),
        migrations.AlterField(
            model_name='member',
            name='has_subscription_letter',
            field=models.BooleanField(default=False, verbose_name='ha firmado la carta?'),
        ),
        migrations.AlterField(
            model_name='member',
            name='legal_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='ID legal'),
        ),
        migrations.AlterField(
            model_name='member',
            name='patron',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary', to='members.Patron', verbose_name='mecenas'),
        ),
        migrations.AlterField(
            model_name='member',
            name='registration_date',
            field=models.DateField(verbose_name='fecha de alta'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=2048, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_info',
            field=models.TextField(blank=True, verbose_name='información de contacto'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='document_number',
            field=models.CharField(blank=True, help_text='CUIT o equivalencia', max_length=317, verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='membership',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='members.Member', verbose_name='membresía'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=317, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='social_media',
            field=models.TextField(blank=True, verbose_name='redes sociales'),
        ),
        migrations.AlterField(
            model_name='patron',
            name='comments',
            field=models.TextField(blank=True, verbose_name='comentarios'),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email',
            field=models.EmailField(max_length=1024, verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='patron',
            name='name',
            field=models.CharField(max_length=317, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='monto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='comments',
            field=models.TextField(blank=True, verbose_name='comentarios'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.PaymentStrategy', verbose_name='estrategia de pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(verbose_name='fecha y hora'),
        ),
        migrations.AlterField(
            model_name='paymentstrategy',
            name='comments',
            field=models.TextField(blank=True, verbose_name='comentarios'),
        ),
        migrations.AlterField(
            model_name='paymentstrategy',
            name='id_in_platform',
            field=models.CharField(max_length=317, verbose_name='ID de plataforma'),
        ),
        migrations.AlterField(
            model_name='paymentstrategy',
            name='patron',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Patron', verbose_name='mecenas'),
        ),
        migrations.AlterField(
            model_name='paymentstrategy',
            name='platform',
            field=models.CharField(choices=[('mercado pago', 'Mercado Pago'), ('todo pago', 'Todo Pago'), ('transfer', 'transferencia bancaria')], default='mercado pago', max_length=317, verbose_name='plataforma'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=317, verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(blank=True, max_length=317, verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='person',
            name='document_number',
            field=models.CharField(blank=True, max_length=317, verbose_name='N° de documento'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=1024, verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=317, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=317, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='person',
            name='marital_status',
            field=models.CharField(blank=True, max_length=317, verbose_name='estado civil'),
        ),
        migrations.AlterField(
            model_name='person',
            name='membership',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Member', verbose_name='membresía'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nationality',
            field=models.CharField(blank=True, max_length=317, verbose_name='nacionalidad'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, help_text='Nick o sobrenombre', max_length=317, verbose_name='nick'),
        ),
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.CharField(blank=True, help_text='Profesión o ocupación', max_length=317, verbose_name='profesión'),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(help_text='Foto o imagen cuadrada para el carnet', null=True, upload_to='pictures', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='person',
            name='province',
            field=models.CharField(blank=True, max_length=317, verbose_name='provincia'),
        ),
        migrations.AlterField(
            model_name='person',
            name='street_address',
            field=models.CharField(blank=True, max_length=317, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='person',
            name='zip_code',
            field=models.CharField(blank=True, max_length=317, verbose_name='código postal'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='monto'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=317, verbose_name='ID de factura'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Member', verbose_name='miembro'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='month',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='mes'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Payment', verbose_name='pago'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2015)], verbose_name='año'),
        ),
    ]
