# Generated by Django 2.0.4 on 2018-05-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20180501_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='email',
            field=models.EmailField(max_length=1024, unique=True, verbose_name='correo electrónico'),
        ),
    ]
