# Generated by Django 2.0.4 on 2018-07-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20180501_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='legal_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID legal'),
        ),
    ]
