# Generated by Django 2.0.4 on 2018-07-11 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20180708_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='first_payment_month',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='primer pago mes', null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='first_payment_year',
            field=models.PositiveSmallIntegerField(default=2015, validators=[django.core.validators.MinValueValidator(2015)], verbose_name='primer pago año', null=True),
            preserve_default=False,
        ),
    ]
