# Generated by Django 2.0.4 on 2018-07-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20180711_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quota',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='quota',
            name='invoice_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=317, verbose_name='ID de factura'),
        ),
    ]
