# Generated by Django 2.0.4 on 2018-07-14 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20180711_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quota',
            options={'get_latest_by': ['year', 'month']},
        ),
    ]
