# Generated by Django 2.0.4 on 2018-07-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20180714_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'get_latest_by': ['timestamp']},
        ),
    ]
