# Generated by Django 2.0.4 on 2018-07-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20180721_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstrategy',
            name='platform',
            field=models.CharField(choices=[('mercado pago', 'Mercado Pago'), ('todo pago', 'Todo Pago'), ('transfer', 'Transferencia Bancaria')], default='mercado pago', max_length=317, verbose_name='plataforma'),
        ),
    ]
