# Generated by Django 2.0.4 on 2018-07-26 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20180723_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='patron',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary', to='members.Patron', verbose_name='mecenas'),
        ),
    ]
