# Generated by Django 2.0.4 on 2018-07-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20180726_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, help_text='Foto o imagen cuadrada para el carnet', null=True, upload_to='pictures', verbose_name='avatar'),
        ),
    ]
