# Generated by Django 2.0.4 on 2018-08-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20180726_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='has_collaborator_acceptance',
            field=models.BooleanField(default=False, verbose_name='ha aceptado ser colaborador?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Adherente', 'Adherente'), ('Estudiante', 'Estudiante'), ('Colaborador', 'Colaborador'), ('Cadete', 'Cadete'), ('Benefactora Platino', 'Benefactora Platino'), ('Benefactora Oro', 'Benefactora Oro'), ('Benefactora Plata', 'Benefactora Plata')], max_length=317, verbose_name='nombre'),
        ),
    ]
