# Generated by Django 2.0.4 on 2018-12-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20180804_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='shutdown_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de baja'),
        ),
    ]
