# Generated by Django 2.0.4 on 2019-01-12 23:03

import django.core.validators
from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_member_shutdown_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='first_payment_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='primer pago mes'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_payment_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2015)], verbose_name='primer pago año'),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, help_text='Foto o imagen cuadrada para el carnet', null=True, upload_to=members.models.picture_upload_path, verbose_name='avatar'),
        ),
    ]
