# Generated by Django 2.0.4 on 2019-02-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_auto_20190127_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, help_text='Nick o sobrenombre', max_length=317, verbose_name='nick'),
        ),
    ]
