# Generated by Django 2.0.4 on 2019-03-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_auto_20190209_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstrategy',
            name='platform',
            field=models.CharField(choices=[('mercado pago', 'Mercado Pago'), ('todo pago', 'Todo Pago'), ('transfer', 'Transferencia Bancaria'), ('credit', 'Crédito Bonificado')], default='mercado pago', max_length=317, verbose_name='plataforma'),
        ),
    ]
