# Generated by Django 2.0.4 on 2019-03-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_auto_20190209_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='application_letter',
            field=models.FileField(blank=True, null=True, upload_to='application_letter', verbose_name='carta de afiliación'),
        ),
    ]
