# Generated by Django 2.0.4 on 2019-04-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_auto_20190313_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_ok',
            field=models.BooleanField(default=False, verbose_name='Factura generada OK'),
        ),
    ]
