# Generated by Django 2.0.12 on 2019-12-08 12:31

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_auto_20190407_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, help_text='Foto o imagen cuadrada para el carnet', null=True, upload_to=members.models.picture_upload_path, validators=[members.models.validate_image_ratio], verbose_name='avatar'),
        ),
    ]
