# Generated by Django 2.0.4 on 2019-06-02 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_member_application_letter'),
        ('members', '0023_auto_20190407_1624'),
    ]

    operations = [
    ]
