# Generated by Django 2.2.11 on 2020-05-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_auto_20191208_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='document_number',
            field=models.CharField(max_length=317, unique=True, verbose_name='N° de documento'),
        ),
    ]
