# Generated by Django 6.1.1 on 2026-10-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_auto_20210509_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Adherente', 'Adherente'), ('Afiliado', 'Afiliado'), ('Benefactora Platino', 'Benefactora Platino'), ('Benefactora Oro', 'Benefactora Oro'), ('Benefactora Plata', 'Benefactora Plata')], max_length=317, verbose_name='nombre'),
        ),
    ]
