# Generated by Django 3.2.25 on 2025-03-23 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wizard', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CamperPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('chat_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pycamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headquarters', models.CharField(max_length=255, unique=True)),
                ('init', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('vote_authorized', models.BooleanField(default=False)),
                ('project_load_authorized', models.BooleanField(default=False)),
                ('wizard_slot_duration', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='WizardTimeframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('wizard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pycamp.camper')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('start', models.DateTimeField()),
                ('current_wizard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pycamp.camper')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('difficulty_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=20)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('repository_url', models.URLField(null=True)),
                ('comms_channel', models.URLField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pycamp.camper')),
                ('presentation_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pycamp.slot')),
            ],
        ),
        migrations.AddField(
            model_name='camper',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camperatpycamp', to='pycamp.camperperson'),
        ),
        migrations.AddField(
            model_name='camper',
            name='pycamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campers', to='pycamp.pycamp'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.BooleanField(blank=True, null=True)),
                ('camper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pycamp.camperperson')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='pycamp.project')),
            ],
            options={
                'unique_together': {('project', 'camper')},
            },
        ),
    ]
