# Generated by Django 2.0.4 on 2019-04-17 18:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('document_number', models.CharField(help_text='CUIT del propietario de la cuenta', max_length=13, verbose_name='CUIT')),
                ('bank_entity', models.CharField(help_text='nombre de la entiedad bancaria', max_length=317, verbose_name='entidad bancaria')),
                ('cbu', models.CharField(max_length=317, verbose_name='CBU')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=317, verbose_name='nombre')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='comisión')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='fecha de incio')),
                ('place', models.CharField(blank=True, max_length=317, verbose_name='lugar')),
                ('category', models.CharField(choices=[('PD', 'PyDay'), ('PCo', 'PyCon'), ('PCa', 'PyCamp'), ('Con', 'Conferencia')], max_length=3, verbose_name='tipo')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('first_name', models.CharField(max_length=317, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=317, verbose_name='apellido')),
                ('account_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.BankAccountData', verbose_name='datos cuenta bancaria')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(related_name='events', to='events.Organizer', verbose_name='organizadores'),
        ),
    ]
