# Generated by Django 2.0.4 on 2019-06-06 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_organizer_group_and_perms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sponsoring',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='events.Sponsoring', verbose_name='patrocinio'),
        ),
    ]
