# Generated by Django 2.0.4 on 2019-06-10 15:03

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_organizer_group_and_perms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsoring',
            options={'permissions': (('close_sponsoring', 'puede cerrar patrocinio'),)},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='close',
        ),
        migrations.AddField(
            model_name='sponsoring',
            name='close',
            field=models.BooleanField(default=False, verbose_name='cerrado'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='document',
            field=models.FileField(upload_to=events.models.invoice_upload_path, verbose_name='archivo'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sponsoring',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='events.Sponsoring', verbose_name='patrocinio'),
        ),
        migrations.AlterField(
            model_name='invoiceaffect',
            name='document',
            field=models.FileField(upload_to=events.models.affect_upload_path, verbose_name='archivo'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='vat_condition',
            field=models.CharField(choices=[('responsable inscripto', 'Responsable Inscripto'), ('monotributo', 'Monotributo'), ('consumidor_final', 'Consumidor Final'), ('exterior', 'Exterior'), ('otro', 'Otro')], max_length=317, verbose_name='condición frente al iva'),
        ),
        migrations.AlterUniqueTogether(
            name='sponsoring',
            unique_together={('sponsorcategory', 'sponsor')},
        ),
    ]
