# Generated by Django 2.0.4 on 2019-06-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190612_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'permissions': (('set_invoice_approved', 'puede aprobar factura'), ('set_invoice_complete_payment', 'puede setear pago completo'), ('set_invoice_partial_payment', 'puede setear pago parcial'))},
        ),
    ]
