# Generated by Django 2.0.4 on 2019-07-12 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import events.helpers.models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20190618_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('description', models.CharField(blank=True, default='', help_text='Descripción del gasto', max_length=317, verbose_name='descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='monto')),
                ('invoice_type', models.CharField(choices=[('A', 'Factura A'), ('B', 'Factura B'), ('C', 'Factura C'), ('Rec', 'Recibo'), ('Tic', 'Ticket')], max_length=5, verbose_name='tipo factura')),
                ('invoice_date', models.DateField(verbose_name='fecha factura')),
                ('invoice', models.FileField(blank=True, upload_to=events.models.expense_upload_path, verbose_name='factura')),
                ('category', models.CharField(choices=[('Prv', 'Gasto proveedor'), ('Ref', 'Reintegro organizador')], max_length=5, verbose_name='tipo gasto')),
            ],
            options={
                'permissions': (('view_expenses', 'puede ver gastos'),),
            },
            bases=(events.helpers.models.SaveReversionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('document', models.FileField(upload_to='media/events/payments/', verbose_name='comprobante')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_payment_changed_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_payment_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(events.helpers.models.SaveReversionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('bankaccountdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.BankAccountData')),
            ],
            options={
                'ordering': ['-created'],
                'permissions': (('view_providers', 'puede ver proveedores'),),
            },
            bases=('events.bankaccountdata',),
        ),
        migrations.CreateModel(
            name='OrganizerRefund',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.Expense')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='events.Organizer', verbose_name='Organizador')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Payment', verbose_name='pago')),
            ],
            options={
                'abstract': False,
            },
            bases=('events.expense',),
        ),
        migrations.CreateModel(
            name='ProviderExpense',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.Expense')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Payment', verbose_name='pago')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='events.Provider', verbose_name='Proveedor')),
            ],
            options={
                'abstract': False,
            },
            bases=('events.expense',),
        ),
        migrations.AddField(
            model_name='expense',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_expense_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_expense_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='events.Event', verbose_name='Evento'),
        ),
    ]
