# Generated by Django 2.0.4 on 2019-07-17 11:36

from django.core.management import call_command
from django.db import migrations
from events.helpers.permissions import (
    create_organizer_group_migrations_wrapped,
    remove_organizer_group
)


def update_permissions(schema, group):
    call_command('update_permissions')


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190715_1440'),
    ]

    operations = [
        migrations.RunPython(update_permissions, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_organizer_group_migrations_wrapped, remove_organizer_group),
    ]

