# Generated by Django 2.0.12 on 2019-12-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20191109_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cancelled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Cancelación'),
        ),
    ]
