# Generated by Django 2.0.12 on 2020-03-02 12:13

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_expense_cancelled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccountdata',
            name='document_number',
            field=models.CharField(help_text='CUIT del propietario de la cuenta.', max_length=13, validators=[events.models.validate_cuit], verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='document_number',
            field=models.CharField(help_text='CUIT del propietario de la cuenta.', max_length=13, unique=True, validators=[events.models.validate_cuit], verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='document_number',
            field=models.CharField(help_text='CUIT', max_length=13, unique=True, validators=[events.models.validate_cuit], verbose_name='CUIT'),
        ),
    ]
