# Generated by Django 3.1.8 on 2021-05-22 14:30

from django.db import migrations, models
import django.db.models.deletion
import events.models
import stdnum.ar.cbu


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200302_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceaffect',
            name='category',
            field=models.CharField(choices=[('Pay', 'Pago'), ('Hold', 'Retención'), ('Oth', 'Otros')], max_length=5, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='cbu',
            field=models.CharField(help_text='CBU de la cuenta', max_length=317, validators=[stdnum.ar.cbu.validate], verbose_name='CBU'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='address',
            field=models.CharField(blank=True, help_text='Dirección completa: calle, número, piso, depto, código postal, partido, localidad, provincia.', max_length=2048, verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='document_number',
            field=models.CharField(help_text='La CUIT', max_length=13, unique=True, validators=[events.models.validate_cuit], verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='other_vat_condition_text',
            field=models.CharField(blank=True, default='', help_text='Especifica otra condición frente al IVA', max_length=317, verbose_name='otra condicion frente al iva'),
        ),
        migrations.AlterField(
            model_name='sponsoring',
            name='sponsorcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_by', to='events.sponsorcategory', verbose_name='categoría'),
        ),
    ]
