# Generated by Django 3.1.13 on 2021-11-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20210522_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='vat_condition',
            field=models.CharField(choices=[('responsable inscripto', 'Responsable Inscripto'), ('consumidor final', 'Consumidor Final'), ('exterior', 'Exterior'), ('otro', 'Otro'), ('responsable no inscripto', 'IVA Responsable no Inscripto'), ('iva no responsable', 'IVA No Responsable'), ('iva sujeto exento', 'IVA Sujeto Exento'), ('sujeto no categorizado', 'Sujeto no Categorizado'), ('monotributo', 'Responsable Monotributo'), ('iva liberado', 'IVA Liberado'), ('iva responsable inscripto agente', 'IVA Responsable Inscripto - Agente de Percepción'), ('pequeño contribuyente eventual', 'Pequeño Contribuyente Eventual'), ('monotributista social', 'Monotributista Social'), ('pequeno contribuyente eventual social', 'Pequeño Contribuyente  Eventual Social')], max_length=317, verbose_name='condición frente al iva'),
        ),
    ]
