# Generated by Django 3.1.13 on 2021-11-22 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20211122_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipDiscounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='descuento (%)')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount', to='events.event')),
            ],
            options={
                'verbose_name_plural': 'Sponsorship Discounts',
            },
        ),
        migrations.AddField(
            model_name='sponsoring',
            name='sponsorship_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.sponsorshipdiscounts', verbose_name='Descuento'),
        ),
    ]
