# Generated by Django 3.1.14 on 2022-10-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20211122_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='real_final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='monto final real en el banco'),
        ),
    ]
